### PR TITLE
Activity start example by package and class name

### PR DESCRIPTION
**Pull request by konstantinov**
Please, add this example to documentation. It may save time for many people. I found it only by reading sources. Thank you.

### CODE REVIEW

**Comment by wesleyakio** [comment]
Thank you for the pull request.
I have not laid a finger to the docs since I forked the project and there are lots of things that are slightly outdated. I'll try to review it as soon as I can.

**Comment by EricDeCoff** [comment]
Are you making these changes to make it compatible to phonegap 3

**Comment by wesleyakio** [comment]
@EricDeCoff Some are for 3.0, some are improvements, some are bugfixes.
It should work properly with 2.9 - 3.2. If it does not, please let me know.

**Comment by EricDeCoff** [comment]
Thank you, I clone it and it worked great
phonegap local plugin add <git address>

Any plans on making an Intel XDK plugin for this

**Pull request merged**
